"""Create categories and products tables

Revision ID: 0d4dcc1e6e50
Revises: 0bc5fa8dbfc9
Create Date: 2026-02-12 15:03:47.075998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4dcc1e6e50'
down_revision: Union[str, Sequence[str], None] = '0bc5fa8dbfc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
