"""Adding fields rating in model products

Revision ID: b73d1296d164
Revises: ac7e4888ca1d
Create Date: 2026-02-24 14:04:01.050479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b73d1296d164'
down_revision: Union[str, Sequence[str], None] = 'ac7e4888ca1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('rating', sa.Float(), server_default=sa.text('0'), nullable=False))
    op.alter_column('reviews', 'grade',
               existing_type=postgresql.ENUM('ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', name='gradeenum'),
               type_=sa.Enum('ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', name='gradeenum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'grade',
               existing_type=sa.Enum('ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', name='gradeenum', native_enum=False),
               type_=postgresql.ENUM('ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', name='gradeenum'),
               existing_nullable=False)
    op.drop_column('products', 'rating')
    # ### end Alembic commands ###
