"""Initial migration for PostgreSQL

Revision ID: e57f785e283e
Revises: 3eb73b2b8cc4
Create Date: 2026-01-26 14:26:59.885763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e57f785e283e'
down_revision: Union[str, Sequence[str], None] = '3eb73b2b8cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
